# Generated by Django 5.0.1 on 2025-07-24 09:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Référence')),
                ('tenant_id', models.UUIDField(db_index=True, verbose_name='ID du tenant')),
                ('client_id', models.UUIDField(db_index=True, verbose_name='ID du client')),
                ('client_name', models.CharField(max_length=255, verbose_name='Nom du client')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée'), ('reportee', 'Reportée')], default='planifiee', max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20, verbose_name='Priorité')),
                ('intervention_type', models.CharField(choices=[('maintenance', 'Maintenance préventive'), ('depannage', 'Dépannage'), ('installation', 'Installation'), ('formation', 'Formation'), ('conseil', 'Conseil'), ('autre', 'Autre')], default='depannage', max_length=20, verbose_name="Type d'intervention")),
                ('scheduled_date', models.DateField(verbose_name='Date planifiée')),
                ('scheduled_time_start', models.TimeField(blank=True, null=True, verbose_name='Heure de début planifiée')),
                ('scheduled_time_end', models.TimeField(blank=True, null=True, verbose_name='Heure de fin planifiée')),
                ('estimated_duration', models.DurationField(blank=True, null=True, verbose_name='Durée estimée')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='Date réelle')),
                ('actual_time_start', models.TimeField(blank=True, null=True, verbose_name='Heure de début réelle')),
                ('actual_time_end', models.TimeField(blank=True, null=True, verbose_name='Heure de fin réelle')),
                ('actual_duration', models.DurationField(blank=True, null=True, verbose_name='Durée réelle')),
                ('address_line_1', models.CharField(max_length=255, verbose_name='Adresse ligne 1')),
                ('address_line_2', models.CharField(blank=True, max_length=255, verbose_name='Adresse ligne 2')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Code postal')),
                ('country', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='Nom du contact')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone du contact')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email du contact')),
                ('technician_id', models.UUIDField(blank=True, null=True, verbose_name='ID du technicien')),
                ('technician_name', models.CharField(blank=True, max_length=255, verbose_name='Nom du technicien')),
                ('equipment', models.TextField(blank=True, verbose_name='Équipement concerné')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('is_billable', models.BooleanField(default=True, verbose_name='Facturable')),
                ('quote_id', models.UUIDField(blank=True, null=True, verbose_name='ID du devis lié')),
                ('invoice_id', models.UUIDField(blank=True, null=True, verbose_name='ID de la facture liée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('created_by', models.UUIDField(blank=True, null=True, verbose_name='Créé par (user_id)')),
                ('updated_by', models.UUIDField(blank=True, null=True, verbose_name='Modifié par (user_id)')),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
                'db_table': 'interventions',
                'ordering': ['-scheduled_date', 'scheduled_time_start'],
                'indexes': [models.Index(fields=['tenant_id'], name='interventio_tenant__653ad2_idx'), models.Index(fields=['client_id'], name='interventio_client__03248e_idx'), models.Index(fields=['status'], name='interventio_status_579a12_idx'), models.Index(fields=['scheduled_date'], name='interventio_schedul_69475a_idx'), models.Index(fields=['technician_id'], name='interventio_technic_8512ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='InterventionMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantité')),
                ('unit', models.CharField(default='pièce', max_length=50, verbose_name='Unité')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix unitaire HT')),
                ('is_billable', models.BooleanField(default=True, verbose_name='Facturable')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='interventions.intervention')),
            ],
            options={
                'verbose_name': "Matériel d'intervention",
                'verbose_name_plural': "Matériels d'intervention",
                'db_table': 'intervention_materials',
            },
        ),
        migrations.CreateModel(
            name='InterventionPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image_data', models.TextField(blank=True, verbose_name='Image (base64)')),
                ('image_url', models.URLField(blank=True, verbose_name="URL de l'image")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('created_by', models.UUIDField(blank=True, null=True, verbose_name='Créé par (user_id)')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='interventions.intervention')),
            ],
            options={
                'verbose_name': "Photo d'intervention",
                'verbose_name_plural': "Photos d'intervention",
                'db_table': 'intervention_photos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterventionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Contenu du rapport')),
                ('conclusion', models.TextField(blank=True, verbose_name='Conclusion')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recommandations')),
                ('technician_signature', models.TextField(blank=True, verbose_name='Signature du technicien (base64)')),
                ('client_signature', models.TextField(blank=True, verbose_name='Signature du client (base64)')),
                ('client_name', models.CharField(blank=True, max_length=255, verbose_name='Nom du signataire client')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Signé le')),
                ('intervention', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='interventions.intervention')),
            ],
            options={
                'verbose_name': "Rapport d'intervention",
                'verbose_name_plural': "Rapports d'intervention",
                'db_table': 'intervention_reports',
            },
        ),
        migrations.CreateModel(
            name='InterventionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée'), ('non_applicable', 'Non applicable')], default='a_faire', max_length=20, verbose_name='Statut')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('estimated_duration', models.DurationField(blank=True, null=True, verbose_name='Durée estimée')),
                ('actual_duration', models.DurationField(blank=True, null=True, verbose_name='Durée réelle')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('completed_by', models.UUIDField(blank=True, null=True, verbose_name='Terminé par (user_id)')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='interventions.intervention')),
            ],
            options={
                'verbose_name': "Tâche d'intervention",
                'verbose_name_plural': "Tâches d'intervention",
                'db_table': 'intervention_tasks',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
